apiVersion: extensions/v1beta
kind: Deployment
metadata:
  name: webserver
  spec:
    replicas: 3
    minReadyseconds: 30
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    template:
      metadata:
        labels:
          apps: web
      spec:
        containers:
        - name: apache
          image: nginx
          port:
          - containerPort: 80